# Generated by Django 4.2.4 on 2023-08-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('poster', models.ImageField(upload_to='posters')),
                ('poster_url', models.URLField()),
                ('description', models.TextField()),
                ('trailer_link', models.URLField(blank=True, default='')),
                ('release_year', models.CharField(max_length=4)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('imdb_reviews', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actors', models.ManyToManyField(related_name='films', to='movie_lib.actor')),
                ('countries', models.ManyToManyField(related_name='films', to='movie_lib.country')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie_lib.director')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='snaps')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snaps', to='movie_lib.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='films', to='movie_lib.genre'),
        ),
    ]
