# Generated by Django 4.2.4 on 2023-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_lib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='films', to='movie_lib.director'),
        ),
    ]
